name: "DevOps / Infrastructure"
description: "CI/CD, infrastructure, monitoring, or deployment task"
title: "[DEVOPS] "
labels: ["type: devops"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What infrastructure or DevOps work is needed"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - "CI/CD Pipeline"
        - "Containerization"
        - "Infrastructure as Code"
        - "Security & Compliance"
        - "Deployment"
        - "Environment Management"
        - "Monitoring & Alerting"
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Target Environment
      options:
        - "Development"
        - "Staging"
        - "Production"
        - "All"
    validations:
      required: true

