name: "User Story"
description: "A feature described from the user's perspective"
title: "[STORY] "
labels: ["type: user-story"]
body:
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: "As a [role], I want [capability] so that [benefit]"
      placeholder: "As a student, I want to select a topic so that I can focus my practice"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "High"
        - "Medium"
        - "Low"
    validations:
      required: true

